// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBffUp8yuyN0uroXIk9BQ6OLgCzHQXhqqo',
    appId: '1:1088008733294:web:60a9f0f6d8dcb52b1a9c7f',
    messagingSenderId: '1088008733294',
    projectId: 'esgi-flutter-13086',
    authDomain: 'esgi-flutter-13086.firebaseapp.com',
    storageBucket: 'esgi-flutter-13086.appspot.com',
    measurementId: 'G-HH4Q1EK6LH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpjK-mnk-c-2l4glot7g9n1IiOS3zEJoY',
    appId: '1:1088008733294:android:686ba4b0367bf5e01a9c7f',
    messagingSenderId: '1088008733294',
    projectId: 'esgi-flutter-13086',
    storageBucket: 'esgi-flutter-13086.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDNi3X8FnZSHlalJgOV83GFzQ_CYWIOOg',
    appId: '1:1088008733294:ios:3810dc1ee784bb791a9c7f',
    messagingSenderId: '1088008733294',
    projectId: 'esgi-flutter-13086',
    storageBucket: 'esgi-flutter-13086.appspot.com',
    iosClientId: '1088008733294-gjbivc62idp9eiad0ojpdg25k1r5hs3o.apps.googleusercontent.com',
    iosBundleId: 'com.example.esgiTpFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDNi3X8FnZSHlalJgOV83GFzQ_CYWIOOg',
    appId: '1:1088008733294:ios:c8f265c4c3a8411d1a9c7f',
    messagingSenderId: '1088008733294',
    projectId: 'esgi-flutter-13086',
    storageBucket: 'esgi-flutter-13086.appspot.com',
    iosClientId: '1088008733294-5mletdhrsh817l69evo0pgd59ei862uj.apps.googleusercontent.com',
    iosBundleId: 'com.example.esgiTpFlutter.RunnerTests',
  );
}
